version: 0.2
phases:
  pre_build:
    commands:
      - echo Restore started on `date`
      - pip install --upgrade awscli
      - dotnet restore HelloWorldWeb/HelloWorldWeb.csproj
  build:
    commands:
      - echo Build started on `date`
      - dotnet publish -c release -o ./build_output HelloWorldWeb/HelloWorldWeb.csproj
artifacts:
  files:
    - HelloWorldWeb/build_output/**/*
    - appspec.yml
